
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    'important-key-concepts',
    {
      type: 'category',
      label: 'Module 1: Robotic Nervous System',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1-nervous-system',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [
        'module-2-digital-twin/intro',
        'module-2-digital-twin/gizmophysics',
        'module-2-digital-twin/unity-simulation',
        'module-2-digital-twin/llm-integration',
        'module-2-digital-twin/vll-logic-design',
        'module-2-digital-twin/multimodal-perception-pipelines',
        'module-2-digital-twin/cognitive-planning-reasoning',
        'module-2-digital-twin/autonomous-humanoid-behavior-orchestration',
        'module-2-digital-twin/digital-twin-architecture-diagrams',
        'module-2-digital-twin/module-2-assessment',
        'module-2-digital-twin/module-1-2-connections'
      ],
    },
    {
      type: 'category',
      label: '3D Visualization',
      items: [
        '3d-visualization',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI Robot Brain',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3-ai-brain',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4-vla',
        },
      ],
    },
  ],
};

export default sidebars;
